[workspace]
members = ["app", "core"]
default-members = ["app"]
resolver = "2"
exclude = ["vendor/gpui-pre", "vendor/mc-launcher-core"]

[patch.crates-io]
gpui-pre = { path = "vendor/gpui-pre" }
mc-launcher-core = { path = "vendor/mc-launcher-core" }

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
gpui-kit = "0.7.0"
futures = "0.3"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "rustls"] }
gpui-devtools = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"
quick-xml = { version = "0.41", features = ["serialize"] }
tracing = "0.1"
mc-launcher-core = "0.1.2"
uuid = { version = "1.23.1", features = ["serde", "v4"] }
tempfile = "3"

[profile.dev.package]
gpui-pre = { opt-level = 3 }
gpui-component = { opt-level = 3 }
gpui-kit = { opt-level = 3 }
gpui-kit-assets = { opt-level = 3 }
gpui-pre-macros = { opt-level = 3 }
gpui-pre-platform = { opt-level = 3 }
rustybuzz = { opt-level = 3 }
taffy = { opt-level = 3 }
ttf-parser = { opt-level = 3 }
