[package]
name = "rs-mc-launcher"
version.workspace = true
edition.workspace = true

[features]
default = ["devtools"]
devtools = ["dep:gpui-devtools"]

[dependencies]
gpui-kit.workspace = true
futures.workspace = true
reqwest.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
mc-launcher-core.workspace = true
uuid.workspace = true
tempfile.workspace = true
image = { version = "0.25.10", default-features = false, features = ["png"] }
gpui-devtools = { workspace = true, optional = true }
rs-mc-launcher-core = { path = "../core" }

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle = "0.6"
windows = { version = "0.61.3", features = ["Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
